-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "readAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "about" SET DEFAULT '',
ALTER COLUMN "accountAge" SET DEFAULT 0,
ALTER COLUMN "githubUrl" SET DEFAULT '',
ALTER COLUMN "linkedinUrl" SET DEFAULT '',
ALTER COLUMN "location" SET DEFAULT '',
ALTER COLUMN "portfolioUrl" SET DEFAULT '',
ALTER COLUMN "twitterUrl" SET DEFAULT '',
ALTER COLUMN "password" SET DEFAULT '';
